<div class="modal fade cash-detail-modal" id="lateFeeDetailModal" tabindex="-1" role="dialog" aria-hidden="true"><div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable"><div class="modal-content">
<div class="modal-header member-modal-header"><div class="member-modal-titlebar"><div class="member-modal-icon"><i class="fas fa-file-alt"></i></div><div><h5 class="modal-title mb-0">Detalle de configuración</h5><small>Ficha completa y auditoría de la regla de mora</small></div></div><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></div>
<div class="modal-body member-modal-body"><div class="cash-detail-hero"><div><span>Configuración de mora</span><h4 id="detailLateFeeCode">-</h4><p id="detailLateFeeName">-</p></div><div id="detailLateFeeStatus">-</div></div>
<div class="cash-detail-summary"><div><span>Días de gracia</span><strong id="detailLateFeeGrace">-</strong></div><div><span>Tipo de cálculo</span><strong id="detailLateFeeType">-</strong></div><div><span>Valor</span><strong id="detailLateFeeValue">-</strong></div></div>
<div class="row"><div class="col-lg-6"><section class="member-detail-card"><h6><i class="fas fa-calculator"></i> Reglas</h6><div class="member-detail-grid"><div><span>Máximo</span><strong id="detailLateFeeMax">-</strong></div><div><span>Automático</span><strong id="detailLateFeeAuto">-</strong></div><div><span>Permite exonerar</span><strong id="detailLateFeeWaiver">-</strong></div></div></section></div>
<div class="col-lg-6"><section class="member-detail-card"><h6><i class="fas fa-user-clock"></i> Auditoría</h6><div class="member-detail-grid"><div><span>Creado por</span><strong id="detailLateFeeCreatedBy">-</strong></div><div><span>Fecha de creación</span><strong id="detailLateFeeCreatedAt">-</strong></div><div><span>Última edición por</span><strong id="detailLateFeeUpdatedBy">-</strong></div><div><span>Última edición</span><strong id="detailLateFeeUpdatedAt">-</strong></div></div></section></div>
<div class="col-12"><section class="member-detail-card mb-0"><h6><i class="fas fa-clipboard-list"></i> Observación</h6><p class="mb-0 text-secondary" id="detailLateFeeObservation">Sin observación.</p></section></div></div></div>
<div class="modal-footer member-modal-footer"><button type="button" class="btn btn-light border" data-dismiss="modal"><i class="fas fa-times mr-1"></i> Cerrar</button></div>
</div></div></div>
