<div class="modal fade cash-modal" id="lateFeeModal" tabindex="-1" role="dialog" aria-hidden="true"><div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable"><div class="modal-content">
<div class="modal-header member-modal-header"><div class="member-modal-titlebar"><div class="member-modal-icon"><i class="fas fa-clock"></i></div><div><h5 class="modal-title mb-0" id="lateFeeModalLabel">Nueva configuración</h5><small>Reglas administrativas para la aplicación de mora</small></div></div><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></div>
<form id="lateFeeForm" autocomplete="off">@csrf<div class="modal-body member-modal-body"><div id="lateFeeErrors" class="alert alert-danger d-none"></div><div class="row">
<div class="col-lg-4"><aside class="cash-side-card"><span class="cash-side-kicker">Resumen de configuración</span><strong id="lateFeeSideCode">Código automático</strong><div class="cash-side-total"><span>Valor</span><strong id="lateFeeSideValue">S/ 0.00</strong></div><div class="cash-side-metrics"><div><span>Gracia</span><strong id="lateFeeSideGrace">0 días</strong></div><div><span>Estado</span><strong id="lateFeeSideStatus">Activo</strong></div></div><p>Al activar esta configuración, cualquier otra configuración activa será desactivada automáticamente.</p></aside></div>
<div class="col-lg-8">
<section class="member-section"><div class="member-section-header"><div><h6><i class="fas fa-info-circle"></i> Información general</h6><p>Identificación, nombre y estado principal.</p></div></div><div class="form-row"><div class="form-group col-md-4"><label>Código</label><input class="form-control form-control-sm" id="lateFeeCode" value="Automático" readonly></div><div class="form-group col-md-5"><label>Nombre <span class="text-danger">*</span></label><input class="form-control form-control-sm" name="name" maxlength="120" required></div><div class="form-group col-md-3"><label>Estado <span class="text-danger">*</span></label><select class="form-control form-control-sm" name="is_active" required><option value="1">Activo</option><option value="0">Inactivo</option></select></div></div></section>
<section class="member-section"><div class="member-section-header"><div><h6><i class="fas fa-calculator"></i> Reglas de cálculo</h6><p>Parámetros visuales de la regla vigente; la fórmula no se modifica.</p></div></div><div class="form-row"><div class="form-group col-md-3"><label>Días de gracia <span class="text-danger">*</span></label><input type="number" class="form-control form-control-sm" name="grace_days" min="0" max="365" value="0" required></div><div class="form-group col-md-4"><label>Tipo de mora <span class="text-danger">*</span></label><select class="form-control form-control-sm" name="calculation_type" required><option value="fixed_daily">Monto fijo diario</option><option value="percentage_daily">Porcentaje diario</option><option value="fixed_once">Monto fijo único</option></select></div><div class="form-group col-md-2"><label>Valor <span class="text-danger">*</span></label><input type="number" class="form-control form-control-sm" name="value" min="0.0001" step="0.0001" required></div><div class="form-group col-md-3"><label>Máximo opcional</label><input type="number" class="form-control form-control-sm" name="max_amount" min="0" step="0.01" placeholder="Sin límite"></div></div><div class="form-row"><div class="form-group col-md-6 mb-0"><label>Aplicar automáticamente</label><select class="form-control form-control-sm" name="auto_apply"><option value="1">Sí</option><option value="0">No</option></select></div><div class="form-group col-md-6 mb-0"><label>Permitir exonerar</label><select class="form-control form-control-sm" name="allow_waiver"><option value="0">No</option><option value="1">Sí</option></select></div></div></section>
<section class="member-section"><div class="member-section-header"><div><h6><i class="fas fa-hand-holding-heart"></i> Exoneración</h6><p>Controla si un usuario autorizado puede justificar la exoneración.</p></div></div><div class="alert alert-light border mb-0 py-2"><i class="fas fa-shield-alt text-primary mr-2"></i> La exoneración seguirá requiriendo el permiso <strong>mora.exonerate</strong>.</div></section>
<section class="member-section mb-0"><div class="member-section-header"><div><h6><i class="fas fa-clipboard-list"></i> Observación</h6><p>Nota administrativa opcional.</p></div></div><textarea class="form-control form-control-sm" name="observation" rows="3" maxlength="1000" placeholder="Observación general"></textarea></section>
</div></div></div><div class="modal-footer member-modal-footer"><button type="button" class="btn btn-light border" data-dismiss="modal"><i class="fas fa-times mr-1"></i> Cancelar</button><button type="submit" class="btn btn-primary"><i class="fas fa-save mr-1"></i> <span id="lateFeeSaveText">Guardar configuración</span></button></div></form>
</div></div></div>
