<div class="modal fade cash-detail-modal" id="profitDetailModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable" role="document"><div class="modal-content">
        <div class="modal-header member-modal-header"><div class="member-modal-titlebar"><div class="member-modal-icon"><i class="fas fa-chart-pie"></i></div><div><h5 class="modal-title mb-0">Detalle de utilidades</h5><small>Distribucion y estado de pagos</small></div></div><button type="button" class="close ml-3" data-dismiss="modal"><span>&times;</span></button></div>
        <div class="modal-body member-modal-body">
            <div class="cash-detail-hero"><div><span>Distribucion</span><h4 id="detailProfitCode">-</h4><p id="detailProfitPeriod">-</p></div><div id="detailProfitStatus">-</div></div>
            <div class="cash-detail-summary"><div><span>Utilidad total</span><strong id="detailProfitTotal">S/ 0.00</strong></div><div><span>Total acción-mes</span><strong id="detailProfitShares">0</strong></div><div><span>Utilidad / acción-mes</span><strong id="detailProfitPerShare">S/ 0.00</strong></div></div>
            <section class="member-detail-card"><h6><i class="fas fa-info-circle"></i> Auditoría</h6><div class="member-detail-grid"><div><span>Calculado el</span><strong id="detailProfitCalculatedAt">-</strong></div><div><span>Calculado por</span><strong id="detailProfitCalculatedBy">-</strong></div><div><span>Aprobado el</span><strong id="detailProfitApprovedAt">-</strong></div><div><span>Aprobado por</span><strong id="detailProfitApprovedBy">-</strong></div><div><span>Inicio</span><strong id="detailProfitStart">-</strong></div><div><span>Fin</span><strong id="detailProfitEnd">-</strong></div></div><div id="detailProfitObservation" class="member-detail-note mt-2">-</div></section>
            <section class="member-detail-card mb-0"><div class="d-flex justify-content-between flex-wrap align-items-center mb-2"><h6><i class="fas fa-users"></i> Detalle por socio</h6><a href="#" id="detailProfitReport" target="_blank" class="btn btn-sm btn-light border"><i class="fas fa-file-alt mr-1"></i> Reporte</a></div><div class="table-responsive"><table class="table table-sm table-hover text-center mb-0"><thead><tr><th>Socio</th><th>DNI</th><th>Acciones</th><th>Meses</th><th>Acción-mes</th><th>%</th><th>Utilidad</th><th>Pagado</th><th>Pendiente</th><th>Estado</th><th></th></tr></thead><tbody id="detailProfitRows"><tr><td colspan="11">Sin detalles.</td></tr></tbody></table></div></section>
        </div>
    </div></div>
</div>
