<?php
use App\Models\{CashMovement,LateFeeSetting,Loan,LoanPayment,Member,User}; use Illuminate\Support\Facades\{Artisan,Gate};
use App\Services\ProfitAvailabilityService;
beforeEach(function(){ Gate::before(fn()=>true); $this->actingAs(User::factory()->create()); LateFeeSetting::create(['name'=>'General','grace_days'=>5,'calculation_type'=>'fixed_daily','value'=>2,'is_active'=>true,'auto_apply'=>true,'allow_waiver'=>true]); });

it('loads the compiled payment summary asset instead of a stale vite development server', function () { $this->get(route('admin.cobros.index'))->assertOk()->assertSee('build/assets/loan-payment-', false)->assertDontSee('5173', false); });
function lateFeeLoan(){ $m=Member::create(['code'=>'SOC-'.fake()->unique()->numerify('######'),'first_name'=>'Socio','full_name'=>'Socio Mora','dni'=>fake()->unique()->numerify('########'),'status'=>'vigente']); $l=Loan::create(['member_id'=>$m->id,'loan_number'=>'PRE-'.fake()->unique()->numerify('######'),'requested_amount'=>50,'approved_amount'=>50,'interest_rate'=>2,'term_months'=>2,'start_date'=>'2026-07-01','first_payment_date'=>'2026-08-10','amortization_method'=>'aleman','fixed_principal'=>25,'total_interest'=>12,'total_amount'=>62,'current_balance'=>62,'status'=>'desembolsado']); $i=$l->installments()->create(['installment_number'=>1,'due_date'=>'2026-08-10','opening_balance'=>50,'principal_amount'=>25,'interest_amount'=>6,'installment_amount'=>31,'remaining_amount'=>31,'closing_balance'=>25,'status'=>'pendiente']); $l->installments()->create(['installment_number'=>2,'due_date'=>'2026-09-10','opening_balance'=>25,'principal_amount'=>25,'interest_amount'=>6,'installment_amount'=>31,'remaining_amount'=>31,'closing_balance'=>0,'status'=>'pendiente']); return [$l,$i]; }
it('creates one consolidated cash movement for a payment with late fee', function () { [$l,$i]=lateFeeLoan(); $this->postJson(route('admin.cobros.store'),['loan_id'=>$l->id,'payment_date'=>'2026-08-20','amount'=>41,'payment_type'=>'cuota','payment_method'=>'efectivo','installment_ids'=>[$i->id]])->assertOk(); $p=LoanPayment::first(); $cash=CashMovement::where('related_id',$p->id)->where('status','registrado')->get(); expect($cash)->toHaveCount(1)->and($cash->first()->category)->toBe('cobro_prestamo')->and((float)$cash->first()->amount)->toBe(41.0)->and($cash->first()->concept)->toContain('Capital S/25.00')->toContain('Mora cobrada S/10.00')->toContain('Mora exonerada S/0.00'); });
it('shows waived late fee in cash traceability without adding it to income', function () { [$l,$i]=lateFeeLoan(); $this->postJson(route('admin.cobros.store'),['loan_id'=>$l->id,'payment_date'=>'2026-08-20','amount'=>31,'payment_type'=>'cuota','payment_method'=>'efectivo','installment_ids'=>[$i->id],'waive_late_fee'=>1,'late_fee_reason'=>'Acuerdo de consejo'])->assertOk(); $p=LoanPayment::first(); $cash=CashMovement::where('related_id',$p->id)->where('status','registrado')->firstOrFail(); expect((float)$cash->amount)->toBe(31.0)->and($cash->concept)->toContain('Mora cobrada S/0.00')->toContain('Mora exonerada S/10.00'); $this->getJson(route('admin.caja.show',$cash))->assertOk()->assertJsonPath('origin.financial_breakdown.capital','S/ 25.00')->assertJsonPath('origin.financial_breakdown.interest','S/ 6.00')->assertJsonPath('origin.financial_breakdown.late_fee','S/ 0.00')->assertJsonPath('origin.financial_breakdown.late_fee_waived','S/ 10.00')->assertJsonPath('origin.financial_breakdown.total','S/ 31.00'); });
it('collects late fee separately in cash and receipt',function(){ [$l,$i]=lateFeeLoan(); $this->postJson(route('admin.cobros.store'),['loan_id'=>$l->id,'payment_date'=>'2026-08-20','amount'=>41,'payment_type'=>'cuota','payment_method'=>'efectivo','installment_ids'=>[$i->id]])->assertOk(); $p=LoanPayment::first(); expect((float)$p->capital_amount)->toBe(25.0)->and((float)$p->interest_amount)->toBe(6.0)->and((float)$p->late_fee_paid)->toBe(10.0)->and((float)$p->amount)->toBe(41.0)->and((float)$l->fresh()->current_balance)->toBe(31.0)->and($i->fresh()->late_fee_status)->toBe('pagada')->and((float)CashMovement::where('related_id',$p->id)->where('status','registrado')->sum('amount'))->toBe(41.0); $this->get(route('admin.cobros.receipt',$p))->assertOk()->assertSee('Capital pagado')->assertSee('Interés pagado')->assertSee('Mora pagada')->assertSee('10.00'); });
it('waives late fee with audit and creates no late fee cash',function(){ [$l,$i]=lateFeeLoan(); $this->postJson(route('admin.cobros.store'),['loan_id'=>$l->id,'payment_date'=>'2026-08-20','amount'=>31,'payment_type'=>'cuota','payment_method'=>'efectivo','installment_ids'=>[$i->id],'waive_late_fee'=>1,'late_fee_reason'=>'Acuerdo de consejo'])->assertOk(); $p=LoanPayment::first(); expect((float)$p->capital_amount)->toBe(25.0)->and((float)$p->interest_amount)->toBe(6.0)->and((float)$p->late_fee_paid)->toBe(0.0)->and((float)$p->late_fee_waived)->toBe(10.0)->and((float)$l->fresh()->current_balance)->toBe(31.0)->and($p->late_fee_reason)->toBe('Acuerdo de consejo')->and($p->late_fee_waived_by)->not->toBeNull()->and(CashMovement::where('related_id',$p->id)->where('category','mora_atraso')->exists())->toBeFalse(); });

it('collects two overdue installments with their complete late fees', function () { [$l] = lateFeeLoan(); $ids = $l->installments()->pluck('id')->all(); $this->postJson(route('admin.cobros.store'), ['loan_id'=>$l->id,'payment_date'=>'2026-10-20','amount'=>264,'payment_type'=>'cuota','payment_method'=>'efectivo','installment_ids'=>$ids])->assertOk(); $p=LoanPayment::first(); expect((float)$p->capital_amount)->toBe(50.0)->and((float)$p->interest_amount)->toBe(12.0)->and((float)$p->late_fee_paid)->toBe(202.0)->and((float)$p->amount)->toBe(264.0)->and((float)$l->fresh()->current_balance)->toBe(0.0); });

it('collects an installment without late fee', function () { [$l,$i] = lateFeeLoan(); $this->postJson(route('admin.cobros.store'), ['loan_id'=>$l->id,'payment_date'=>'2026-08-10','amount'=>31,'payment_type'=>'cuota','payment_method'=>'efectivo','installment_ids'=>[$i->id]])->assertOk(); $p=LoanPayment::first(); expect((float)$p->capital_amount)->toBe(25.0)->and((float)$p->interest_amount)->toBe(6.0)->and((float)$p->late_fee_paid)->toBe(0.0)->and((float)$l->fresh()->current_balance)->toBe(31.0); });

it('exposes every numeric component required by the payment summary', function () { [$l] = lateFeeLoan(); $this->getJson(route('admin.cobros.loan.installments', $l) . '?payment_date=2026-08-20')->assertOk()->assertJsonPath('installments.0.principal_pending', '25.00')->assertJsonPath('installments.0.interest_pending', '6.00')->assertJsonPath('installments.0.remaining_amount', '31.00')->assertJsonPath('installments.0.late_fee', '10.00')->assertJsonPath('installments.0.total_due', '41.00'); });

it('matches the real 339 balance case with complete detail receipt and cash breakdown', function () { [$l,$i] = lateFeeLoan(); LateFeeSetting::query()->update(['value'=>1]); $l->update(['current_balance'=>339]); $i->update(['due_date'=>'2026-06-01']); $this->postJson(route('admin.cobros.store'), ['loan_id'=>$l->id,'payment_date'=>'2026-07-19','amount'=>74,'payment_type'=>'cuota','payment_method'=>'efectivo','installment_ids'=>[$i->id]])->assertOk(); $p=LoanPayment::first(); expect((float)$p->capital_amount)->toBe(25.0)->and((float)$p->interest_amount)->toBe(6.0)->and((float)$p->late_fee_paid)->toBe(43.0)->and((float)$p->amount)->toBe(74.0)->and((float)$p->previous_loan_balance)->toBe(62.0)->and((float)$p->new_loan_balance)->toBe(31.0)->and((float)$l->fresh()->current_balance)->toBe(31.0)->and($i->fresh()->status)->toBe('pagado')->and((float)CashMovement::where('related_id',$p->id)->where('status','registrado')->sum('amount'))->toBe(74.0); $this->getJson(route('admin.cobros.show',$p))->assertOk()->assertJsonPath('previous_loan_balance_formatted','S/ 62.00')->assertJsonPath('new_loan_balance_formatted','S/ 31.00')->assertJsonPath('details.0.due_date','01/06/2026')->assertJsonPath('details.0.late_fee_days',43)->assertJsonPath('details.0.amount_paid','S/ 74.00'); $cash=CashMovement::where('related_id',$p->id)->first(); $this->getJson(route('admin.caja.show',$cash))->assertOk()->assertJsonPath('origin.financial_breakdown.capital','S/ 25.00')->assertJsonPath('origin.financial_breakdown.interest','S/ 6.00')->assertJsonPath('origin.financial_breakdown.late_fee','S/ 43.00')->assertJsonPath('origin.financial_breakdown.total','S/ 74.00'); $this->get(route('admin.cobros.receipt',$p))->assertOk()->assertSee('Saldo anterior préstamo')->assertSee('Saldo posterior préstamo')->assertSee('El total pagado incluye capital, interés y mora')->assertSee('25.00')->assertSee('6.00')->assertSee('43.00')->assertSee('74.00')->assertSee('62.00')->assertSee('31.00'); });
it('generates distributable profit only from interest and late fees on the real payment date', function () { [$l,$i]=lateFeeLoan(); LateFeeSetting::query()->update(['value'=>1]); $i->update(['due_date'=>'2026-06-01']); $this->postJson(route('admin.cobros.store'),['loan_id'=>$l->id,'payment_date'=>'2026-07-19','amount'=>74,'payment_type'=>'cuota','payment_method'=>'efectivo','installment_ids'=>[$i->id]])->assertOk(); $service=app(ProfitAvailabilityService::class); $june=$service->summary('2026-06-01','2026-06-30'); $july=$service->summary('2026-07-01','2026-07-31'); expect($june['generated'])->toBe(0.0)->and($july['interestCollected'])->toBe(6.0)->and($july['lateFeesCollected'])->toBe(43.0)->and($july['generated'])->toBe(49.0); $this->getJson(route('admin.utilidades.availability',['start_date'=>'2026-07-01','end_date'=>'2026-07-31']))->assertOk()->assertJsonPath('generated',49)->assertJsonPath('available',49); $this->getJson(route('admin.utilidades.sources',['start_date'=>'2026-07-01','end_date'=>'2026-07-31']))->assertOk()->assertJsonCount(1)->assertJsonPath('0.interest',6)->assertJsonPath('0.late_fee',43)->assertJsonPath('0.total',49); });
it('does not count waived late fees or annulled payments as profit', function () { [$l,$i]=lateFeeLoan(); $this->postJson(route('admin.cobros.store'),['loan_id'=>$l->id,'payment_date'=>'2026-08-20','amount'=>31,'payment_type'=>'cuota','payment_method'=>'efectivo','installment_ids'=>[$i->id],'waive_late_fee'=>1,'late_fee_reason'=>'Acuerdo'])->assertOk(); $service=app(ProfitAvailabilityService::class); expect($service->summary('2026-08-01','2026-08-31')['generated'])->toBe(6.0); $this->postJson(route('admin.cobros.annul',LoanPayment::first()))->assertOk(); expect($service->summary('2026-08-01','2026-08-31')['generated'])->toBe(0.0); });
it('annuls a late fee payment and fully restores amounts used by the next payment',function(){ [$l,$i]=lateFeeLoan(); $this->postJson(route('admin.cobros.store'),['loan_id'=>$l->id,'payment_date'=>'2026-08-20','amount'=>41,'payment_type'=>'cuota','payment_method'=>'efectivo','installment_ids'=>[$i->id]])->assertOk(); $p=LoanPayment::first(); $this->postJson(route('admin.cobros.annul',$p))->assertOk(); $i->refresh(); expect((float)$i->capital_paid)->toBe(0.0)->and((float)$i->interest_paid)->toBe(0.0)->and((float)$i->paid_amount)->toBe(0.0)->and((float)$i->remaining_amount)->toBe(31.0)->and((float)$i->late_fee_paid)->toBe(0.0)->and($i->status)->toBe('pendiente')->and($i->paid_at)->toBeNull()->and((float)$l->fresh()->current_balance)->toBe(62.0)->and($p->receipt->fresh()->status)->toBe('anulado')->and(CashMovement::where('related_id',$p->id)->where('status','registrado')->exists())->toBeFalse(); $this->getJson(route('admin.cobros.loan.installments',$l).'?payment_date=2026-08-20')->assertOk()->assertJsonPath('installments.0.principal_pending','25.00')->assertJsonPath('installments.0.interest_pending','6.00')->assertJsonPath('installments.0.total_due','41.00'); });

it('repairs legacy installments contaminated by an annulled payment', function () { [$l,$i]=lateFeeLoan(); $this->postJson(route('admin.cobros.store'),['loan_id'=>$l->id,'payment_date'=>'2026-08-20','amount'=>41,'payment_type'=>'cuota','payment_method'=>'efectivo','installment_ids'=>[$i->id]])->assertOk(); $p=LoanPayment::first(); $p->update(['status'=>'anulado']); $i->update(['capital_paid'=>25,'interest_paid'=>6,'paid_amount'=>31,'remaining_amount'=>31,'status'=>'pendiente']); Artisan::call('loans:recalculate-schedules',['--loan'=>$l->id]); $i->refresh(); expect((float)$i->capital_paid)->toBe(0.0)->and((float)$i->interest_paid)->toBe(0.0)->and((float)$i->paid_amount)->toBe(0.0)->and((float)$i->remaining_amount)->toBe(31.0)->and($i->status)->toBe('pendiente'); });
it('includes overdue late fee in liquidation and exempts future interest',function(){ [$l,$i]=lateFeeLoan(); $this->postJson(route('admin.cobros.store'),['loan_id'=>$l->id,'payment_date'=>'2026-08-20','amount'=>66,'payment_type'=>'liquidacion','payment_method'=>'efectivo'])->assertOk(); $p=LoanPayment::first(); expect((float)$p->capital_amount)->toBe(50.0)->and((float)$p->interest_amount)->toBe(6.0)->and((float)$p->late_fee_paid)->toBe(10.0)->and((float)$p->interest_exonerated_amount)->toBe(6.0)->and($l->fresh()->status)->toBe('pagado'); });

