var tableAdministrative;
var administrativeAnnulId=null;
$(function(){
 tableAdministrative=$('#tableAdministrative').DataTable({processing:true,serverSide:true,ajax:{url:window.administrativeRoutes.list,data:d=>{
  d.date_from=$('#admin_filter_date_from').val();d.date_to=$('#admin_filter_date_to').val();d.type=$('#admin_filter_type').val();d.member_id=$('#admin_filter_member_id').val();d.status=$('#admin_filter_status').val();d.payment_method=$('#admin_filter_payment_method').val();
 }},columns:[{data:'DT_RowIndex',orderable:false,searchable:false},{data:'code'},{data:'movement_date'},{data:'type'},{data:'member_name'},{data:'concept'},{data:'payment_method'},{data:'amount'},{data:'status'},{data:'acciones',orderable:false,searchable:false}],order:[[2,'desc']],language:{url:'https://cdn.datatables.net/plug-ins/1.13.8/i18n/es-ES.json'}});
 loadAdministrativeSummary();
 $('[id^="admin_filter_"]').on('change',()=>{tableAdministrative.ajax.reload();loadAdministrativeSummary()});
 $('#btnClearAdministrativeFilters').on('click',()=>{$('[id^="admin_filter_"]').val('');tableAdministrative.ajax.reload();loadAdministrativeSummary()});
 $('#btnNewAdministrative').on('click',()=>{resetAdministrative();$.get(window.administrativeRoutes.nextCode,r=>{$('[name="code"]').val(r.code);$('#administrativeSideCode').text(r.code)});$('#administrativeModal').modal('show')});
 $('#administrativeForm [name="amount"]').on('input',function(){$('#administrativeSideAmount').text(`S/ ${(parseFloat(this.value)||0).toFixed(2)}`)});
 $('#administrativeVoucher').on('change',function(){$('#administrativeVoucherName').text(this.files[0]?.name||'JPG, PNG, WEBP o PDF - max. 4 MB')});
 $('#administrativeForm').on('submit',function(e){e.preventDefault();const id=$(this).attr('data-id'),data=new FormData(this);let url=window.administrativeRoutes.store;if(id){url=`${window.administrativeRoutes.base}/${id}`;data.append('_method','PUT')}$.ajax({url,type:'POST',data,processData:false,contentType:false}).done(r=>{$('#administrativeModal').modal('hide');tableAdministrative.ajax.reload(null,false);loadAdministrativeSummary();toastAdmin(r.message,'success')}).fail(showAdminError)});
 $(document).on('click','.editAdministrative',function(){$.get(`${window.administrativeRoutes.base}/${$(this).data('id')}/edit`,m=>{fillAdministrative(m);$('#administrativeModal').modal('show')}).fail(showAdminError)});
 $(document).on('click','.showAdministrative',function(){$.get(`${window.administrativeRoutes.base}/${$(this).data('id')}`,m=>{fillAdministrativeDetail(m);$('#administrativeDetailModal').modal('show')}).fail(showAdminError)});
 $(document).on('click','.annulAdministrative',function(){administrativeAnnulId=$(this).data('id');$('#administrativeCancellationReason').val('');$('#administrativeAnnulModal').modal('show')});
 $('#confirmAdministrativeAnnul').on('click',function(){const reason=$('#administrativeCancellationReason').val().trim();if(!reason)return Swal.fire('Atención','Ingrese el motivo de anulación.','warning');$.post(`${window.administrativeRoutes.base}/${administrativeAnnulId}/anular`,{cancellation_reason:reason}).done(r=>{$('#administrativeAnnulModal').modal('hide');tableAdministrative.ajax.reload(null,false);loadAdministrativeSummary();toastAdmin(r.message,'success')}).fail(showAdminError)});
});
function resetAdministrative(){const f=$('#administrativeForm');f[0].reset();f.removeAttr('data-id');f.find('[name="movement_date"]').val(new Date().toISOString().slice(0,10));f.find('[name="code"]').val(window.administrativeRoutes.nextCodeValue);$('#administrativeSideCode').text(window.administrativeRoutes.nextCodeValue);$('#administrativeSideAmount').text('S/ 0.00');$('#administrative-errors').addClass('d-none').empty()}
function fillAdministrative(m){resetAdministrative();const f=$('#administrativeForm').attr('data-id',m.id);['code','movement_date','type','member_id','concept','amount','payment_method','payment_reference','observation'].forEach(k=>f.find(`[name="${k}"]`).val(m[k]??''));$('#administrativeSideCode').text(m.code);$('#administrativeSideAmount').text(m.amount_formatted)}
function fillAdministrativeDetail(m){$('#detailAdministrativeCode').text(m.code);$('#detailAdministrativeConcept').text(m.concept);$('#detailAdministrativeStatus').html(`<span class="badge badge-${m.status==='anulado'?'danger':'success'}">${m.status}</span>`);$('#detailAdministrativeType').text(m.type_label);$('#detailAdministrativeAmount').text(m.amount_formatted);$('#detailAdministrativeSource').text(m.source_label);$('#detailAdministrativeDate').text(m.movement_date_formatted);$('#detailAdministrativeMember').text(m.member_name||'-');$('#detailAdministrativeMethod').text(m.payment_method_label);$('#detailAdministrativeReference').text(m.payment_reference||'-');$('#detailAdministrativeCash').text(m.cash_movement_number||'-');$('#detailAdministrativeUser').text(m.created_by_name||'-');$('#detailAdministrativeObservation').text(m.observation||'-');$('#detailAdministrativeCancellation').text(m.cancellation_reason?`${m.cancellation_reason} (${m.cancelled_at||'-'})`:'-');$('#detailAdministrativeAutomatic').toggleClass('d-none',!m.is_automatic)}
function loadAdministrativeSummary(){$.get(window.administrativeRoutes.summary,{date_from:$('#admin_filter_date_from').val(),date_to:$('#admin_filter_date_to').val()},s=>{$('#adminSummaryBalance').text(`S/ ${s.balance}`);$('#adminSummaryIncome').text(`S/ ${s.income}`);$('#adminSummaryExpense').text(`S/ ${s.expense}`);$('#adminSummaryMonth').text(s.month_movements)})}
function showAdminError(x){if(x.status===422&&x.responseJSON?.errors){$('#administrative-errors').removeClass('d-none').html('<ul class="mb-0">'+Object.values(x.responseJSON.errors).map(e=>`<li>${e[0]}</li>`).join('')+'</ul>');return}Swal.fire('Error',x.responseJSON?.message||'No se pudo completar la operación.','error')}
function toastAdmin(message,icon){Swal.fire({title:message,icon,toast:true,position:'top-end',showConfirmButton:false,timer:3000})}
