<div class="modal fade cash-detail-modal" id="loanDetailModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable" role="document"><div class="modal-content">
        <div class="modal-header member-modal-header"><div class="member-modal-titlebar"><div class="member-modal-icon"><i class="fas fa-file-invoice-dollar"></i></div><div><h5 class="modal-title mb-0">Detalle del prestamo</h5><small>Ficha administrativa y financiera</small></div></div><button type="button" class="close ml-3" data-dismiss="modal"><span>&times;</span></button></div>
        <div class="modal-body member-modal-body">
            <div class="cash-detail-hero"><div><span>Prestamo real</span><h4 id="detailLoanCode">-</h4><p id="detailLoanMember">-</p></div><div id="detailLoanStatus">-</div></div>
            <div class="cash-detail-summary"><div><span>Monto aprobado</span><strong id="detailLoanApproved">S/ 0.00</strong></div><div><span>Capital pendiente</span><strong id="detailLoanPendingCapital">S/ 0.00</strong></div><div><span>Interes futuro estimado</span><strong id="detailLoanEstimatedInterest">S/ 0.00</strong></div><div><span>Saldo por cobrar estimado</span><strong id="detailLoanBalance">S/ 0.00</strong></div></div>
            <div class="row">
                <div class="col-lg-6"><section class="member-detail-card"><h6><i class="fas fa-id-card"></i> Datos</h6><div class="member-detail-grid"><div><span>DNI</span><strong id="detailLoanDni">-</strong></div><div><span>Tasa</span><strong id="detailLoanRate">-</strong></div><div><span>Plazo</span><strong id="detailLoanTerm">-</strong></div><div><span>Primera cuota</span><strong id="detailLoanFirstDate">-</strong></div><div><span>Aprobado</span><strong id="detailLoanApprovedAt">-</strong></div><div><span>Desembolsado</span><strong id="detailLoanDisbursedAt">-</strong></div></div></section></div>
                <div class="col-lg-6"><section class="member-detail-card"><h6><i class="fas fa-users-cog"></i> Auditoria</h6><div class="member-detail-grid"><div><span>Registrado por</span><strong id="detailLoanCreatedBy">-</strong></div><div><span>Aprobado por</span><strong id="detailLoanApprovedBy">-</strong></div><div><span>Desembolsado por</span><strong id="detailLoanDisbursedBy">-</strong></div><div><span>Liquidado por</span><strong id="detailLoanLiquidatedBy">-</strong></div><div><span>Fecha liquidacion</span><strong id="detailLoanLiquidatedAt">-</strong></div><div><span>Registro liquidacion</span><strong id="detailLoanLiquidationCreatedAt">-</strong></div></div></section></div>
                <div class="col-12"><section class="member-detail-card loan-closing-summary"><div class="member-detail-card-heading"><div><h6><i class="fas fa-check-double"></i> Resumen de cierre / liquidacion</h6><p>Comparacion entre la proyeccion original y los cobros reales.</p></div><span id="detailLoanFinalStatus" class="badge badge-success">-</span></div><div class="cash-detail-summary"><div><span>Total proyectado original</span><strong id="detailLoanProjectedTotal">S/ 0.00</strong></div><div><span>Total pagado real</span><strong id="detailLoanRealPaid">S/ 0.00</strong></div><div><span>Capital pagado</span><strong id="detailLoanCapitalPaid">S/ 0.00</strong></div><div><span>Interes pagado</span><strong id="detailLoanInterestPaid">S/ 0.00</strong></div><div><span>Interes exonerado por adelanto</span><strong id="detailLoanAdvanceExonerated">S/ 0.00</strong></div><div><span>No cobrado por liquidacion</span><strong id="detailLoanLiquidationExonerated">S/ 0.00</strong></div><div><span>Saldo final</span><strong id="detailLoanFinalBalance">S/ 0.00</strong></div></div></section></div>
                <div class="col-12"><section class="member-detail-card"><div class="member-detail-card-heading"><div><h6><i class="fas fa-cash-register"></i> Cobros realizados</h6><p>Pagos, recibos y comprobantes relacionados con este prestamo.</p></div></div><div class="table-responsive"><table class="table table-sm table-hover mb-0"><thead><tr><th>Codigo</th><th>Fecha</th><th>Tipo</th><th class="text-right">Monto</th><th>Registrado por</th><th class="text-right">Acciones</th></tr></thead><tbody id="detailLoanPaymentsRows"><tr><td colspan="6" class="text-center text-muted">Sin cobros registrados.</td></tr></tbody></table></div></section></div>
                <div class="col-12"><section class="member-detail-card"><h6><i class="fas fa-money-check-alt"></i> Desembolso</h6><div id="detailLoanDisbursementEmpty" class="alert alert-light border mb-0">Este prestamo aun no ha sido desembolsado.</div><div id="detailLoanDisbursementInfo" class="d-none"><div class="member-detail-grid mb-3"><div><span>Fecha</span><strong id="detailLoanDisbursementDate">-</strong></div><div><span>Usuario</span><strong id="detailLoanDisbursementUser">-</strong></div><div><span>Metodo pago</span><strong id="detailLoanDisbursementMethod">-</strong></div><div><span>Referencia</span><strong id="detailLoanDisbursementReference">-</strong></div></div><div id="detailLoanVoucherPreview" class="loan-detail-voucher mb-3"></div><div class="btn-group btn-group-sm" role="group"><a href="#" target="_blank" class="btn btn-light border disabled" id="detailLoanVoucherLink"><i class="fas fa-eye mr-1"></i> Sin comprobante</a><a href="#" class="btn btn-light border disabled" id="detailLoanVoucherDownload"><i class="fas fa-download mr-1"></i> Descargar</a><a href="#" target="_blank" class="btn btn-light border disabled" id="detailLoanReceiptLink"><i class="fas fa-receipt mr-1"></i> Sin recibo</a></div></div></section></div>
                <div class="col-12"><section class="member-detail-card"><h6><i class="fas fa-user-check"></i> Evaluacion de prestamo</h6><div class="member-detail-grid"><div><span>Tipo de socio</span><strong id="detailLoanMemberType">-</strong></div><div><span>Aportes registrados</span><strong id="detailLoanContributionCount">-</strong></div><div><span>Total aportado valido</span><strong id="detailLoanContributions">-</strong></div><div><span>Limite sin garante</span><strong id="detailLoanLimit">-</strong></div><div><span>Requiere garante</span><strong id="detailLoanRequiresGuarantor">-</strong></div><div><span>Motivo</span><strong id="detailLoanGuarantorReason">-</strong></div><div><span>Garante socio</span><strong id="detailLoanGuarantor">-</strong></div><div><span>Aportes del garante</span><strong id="detailLoanGuarantorContributions">-</strong></div></div></section></div>
                <div class="col-12"><section class="member-detail-card mb-0"><h6><i class="fas fa-clipboard-list"></i> Motivo y observacion</h6><div class="member-detail-note"><strong id="detailLoanPurpose">-</strong><br><span id="detailLoanObservation">-</span></div></section></div>
            </div>
        </div>
    </div></div>
</div>
