<!doctype html>
<html lang="es">
<head>
    @php
        $isFinal = $closure->status === 'cerrado';
        $isAnnulled = $closure->status === 'anulado';
        $pendingRegularization = $closure->status === 'pendiente_regularizacion' || ($closure->status === 'calculado' && ((float) $closure->final_balance < 0 || (float) $closure->total_against > (float) $closure->total_in_favor));
        $statusLabel = $isAnnulled ? 'Anulado' : ($isFinal ? 'Confirmado' : ($pendingRegularization ? 'Pendiente de regularización' : 'Calculado'));
        $documentTitle = $isAnnulled ? 'Registro anulado de retiro y cierre' : ($isFinal ? 'Constancia de retiro y cierre de cuenta' : 'Calculo preliminar de retiro');
        $resultLabel = (float) $closure->final_balance > 0 ? 'Saldo a favor del socio' : ((float) $closure->final_balance < 0 ? 'Saldo en contra del socio' : 'Sin saldo');
        $paymentLabel = ['efectivo' => 'Efectivo', 'yape' => 'Yape', 'plin' => 'Plin', 'transferencia' => 'Transferencia', 'cheque' => 'Cheque', 'otro' => 'Otro'][$closure->payment_method] ?? 'No aplica';
        $movement = $closure->cashMovement;
    @endphp
    <meta charset="utf-8">
    <title>{{ $documentTitle }} {{ $closure->code }}</title>
    <style>
        @page{margin:0}*{box-sizing:border-box}body{margin:0;background:#fff;color:#263b49;font-family:DejaVu Sans,Arial,sans-serif;font-size:9px}.page{padding:24px 28px 20px}.header{padding:17px 20px;background:#173f62;color:#fff}.header table{width:100%;border:0}.header td{border:0;padding:0;color:#fff}.brand{font-size:23px;font-weight:800}.title{margin-top:2px;font-size:14px}.meta{text-align:right;line-height:1.7}.status{display:inline-block;margin-top:4px;padding:3px 8px;border-radius:10px;background:#fff;color:#173f62;font-size:8px;font-weight:bold}.notice{margin:10px 0;padding:8px 10px;border:1px solid #b9d7e7;background:#eef7fc;color:#225976;border-radius:5px;font-weight:bold}.notice.danger{border-color:#e8b5b5;background:#fff1f1;color:#982f2f}.notice.warning{border-color:#edcf8d;background:#fff8e8;color:#8a5a0b}.section-title{margin:13px 0 6px;padding-bottom:4px;border-bottom:2px solid #d9e6ee;color:#174b69;font-size:11px;font-weight:bold}.info{width:100%;border-collapse:separate;border-spacing:4px;margin:0 -4px}.info td{width:25%;padding:7px 8px;border:1px solid #dfe8ee;border-radius:4px;background:#f8fafc;vertical-align:top}.label{display:block;margin-bottom:2px;color:#70818d;font-size:7px;font-weight:bold;text-transform:uppercase}.value{font-size:9px;font-weight:bold;color:#263e4d}.summary{width:100%;border-collapse:separate;border-spacing:4px;margin:0 -4px}.summary td{width:25%;padding:8px;border:1px solid #dbe6ec;background:#f7fafc}.summary span{display:block;color:#697b87;font-size:7px;font-weight:bold;text-transform:uppercase}.summary strong{display:block;margin-top:3px;color:#174b69;font-size:12px}.summary .favor{background:#edf9f3;border-color:#b9e2ce}.summary .favor strong{color:#14734d}.summary .against{background:#fff3f3;border-color:#ecc5c5}.summary .against strong{color:#9d3030}.summary .balance{background:#edf6fc;border-color:#a9ccdf}.detail{width:100%;border-collapse:collapse}.detail th{padding:6px;background:#204f6b;color:#fff;text-align:left;font-size:7px}.detail td{padding:6px;border-bottom:1px solid #dfe7ec;vertical-align:top;font-size:8px}.detail .money{text-align:right;white-space:nowrap}.muted{color:#74838d;font-size:7px}.notes{padding:8px 10px;border:1px solid #dce6ec;background:#f9fbfc;line-height:1.6}.audit{width:100%;border-collapse:separate;border-spacing:4px;margin:0 -4px}.audit td{width:33.33%;padding:7px;border:1px solid #e0e8ed;background:#fafcfd;vertical-align:top}.cash{padding:8px;border:1px solid #bcd9e8;background:#f0f8fc}.signatures{width:100%;margin-top:32px;text-align:center}.signatures td{width:50%;padding:0 35px;border:0}.sign-line{padding-top:6px;border-top:1px solid #40515c}.footer{margin-top:14px;text-align:center;color:#86939b;font-size:7px}.avoid-break{page-break-inside:avoid}
    </style>
</head>
<body>
    <div class="header"><table><tr><td><div class="brand">SysCaC</div><div class="title">{{ $documentTitle }}</div></td><td class="meta"><strong>{{ $closure->code }}</strong><br>Fecha de cierre: {{ optional($closure->closure_date)->format('d/m/Y') ?: 'No aplica' }}<br><span class="status">{{ $statusLabel }}</span></td></tr></table></div>
    <div class="page">
        @if($isAnnulled)
            <div class="notice danger">Este cierre fue anulado y se conserva únicamente como historial de auditoría.</div>
        @elseif($pendingRegularization)
            <div class="notice warning">El socio tiene saldo en contra. No se puede confirmar el retiro hasta regularizar la deuda pendiente.</div>
        @elseif($isFinal)
            <div class="notice">Cierre confirmado correctamente. El socio fue marcado como retirado{{ $movement ? ' y se generó el movimiento de Caja correspondiente' : ' sin movimiento de Caja' }}.</div>
        @else
            <div class="notice warning">No valido como constancia definitiva. El socio continúa vigente hasta confirmar el cierre.</div>
        @endif

        <div class="section-title">Datos del socio y del cierre</div>
        <table class="info"><tr><td><span class="label">Socio</span><span class="value">{{ $closure->member?->full_name ?: 'No aplica' }}</span></td><td><span class="label">Código de socio</span><span class="value">{{ $closure->member?->code ?: 'No aplica' }}</span></td><td><span class="label">DNI</span><span class="value">{{ $closure->member?->dni ?: 'No aplica' }}</span></td><td><span class="label">Resultado</span><span class="value">{{ $resultLabel }}</span></td></tr><tr><td><span class="label">Fecha de ingreso</span><span class="value">{{ optional($closure->member?->admission_date)->format('d/m/Y') ?: 'No aplica' }}</span></td><td><span class="label">Fecha de retiro</span><span class="value">{{ optional($closure->retirement_date)->format('d/m/Y') ?: 'No aplica' }}</span></td><td><span class="label">Fecha de cálculo</span><span class="value">{{ optional($closure->created_at)->format('d/m/Y H:i') ?: 'No aplica' }}</span></td><td><span class="label">Fecha de confirmación</span><span class="value">{{ optional($closure->closed_at)->format('d/m/Y H:i') ?: 'No aplica' }}</span></td></tr></table>

        <div class="section-title">Resumen financiero</div>
        <table class="summary"><tr><td><span>Aportes devueltos</span><strong>S/ {{ number_format((float) $closure->total_contributions, 2) }}</strong></td><td class="against"><span>Deudas descontadas</span><strong>S/ {{ number_format((float) $closure->pending_loans_amount, 2) }}</strong></td><td class="favor"><span>Utilidad pagada ahora</span><strong>S/ {{ number_format((float) $closure->utility_paid_now, 2) }}</strong></td><td><span>Utilidad pendiente anual</span><strong>S/ {{ number_format($closure->utility_mode === 'pending' ? (float) $closure->utility_estimated_amount : 0, 2) }}</strong></td></tr><tr><td class="favor"><span>Total a favor</span><strong>S/ {{ number_format((float) $closure->total_in_favor, 2) }}</strong></td><td class="against"><span>Total en contra</span><strong>S/ {{ number_format((float) $closure->total_against, 2) }}</strong></td><td class="balance"><span>Total entregado al socio</span><strong>{{ (float) $closure->final_balance < 0 ? '- ' : '' }}S/ {{ number_format(abs((float) $closure->final_balance), 2) }}</strong></td><td><span>Estado</span><strong>{{ $statusLabel }}</strong></td></tr></table>

        <h3>Utilidad proporcional acumulada</h3>
        <table class="info"><tr><td><span class="label">Acciones consideradas</span><span class="value">{{ number_format((float) $closure->utility_actions_considered, 4) }}</span></td><td><span class="label">Meses productivos cerrados</span><span class="value">{{ $closure->utility_productive_months }}</span></td><td><span class="label">Acción-mes del socio</span><span class="value">{{ number_format((float) $closure->utility_action_month, 4) }}</span></td><td><span class="label">Utilidad disponible</span><span class="value">S/ {{ number_format((float) $closure->utility_available_snapshot, 2) }}</span></td></tr><tr><td><span class="label">Utilidad estimada</span><span class="value">S/ {{ number_format((float) $closure->utility_estimated_amount, 2) }}</span></td><td><span class="label">Utilidad pagada ahora</span><span class="value">S/ {{ number_format((float) $closure->utility_paid_now, 2) }}</span></td><td><span class="label">Modalidad</span><span class="value">{{ $closure->utility_mode === 'provisional' ? 'Provisional' : 'Pendiente de cierre anual' }}</span></td><td><span class="label">Estado</span><span class="value">{{ $closure->utility_status === 'liquidada' ? 'Liquidada' : ($closure->utility_status === 'provisional' ? 'Provisional' : ($closure->utility_status === 'pendiente_cierre_anual' ? 'Pendiente de cierre anual' : 'No calculada')) }}</span></td></tr></table>

        <div class="section-title">Detalle del cálculo</div>
        <table class="detail"><thead><tr><th>Tipo</th><th>Descripción</th><th>A favor</th><th>En contra</th><th>Origen</th><th>Código relacionado</th></tr></thead><tbody>@forelse($details as $detail)<tr><td><strong>{{ $detail['item_type_label'] }}</strong></td><td>{{ $detail['description'] }}</td><td class="money">{{ $detail['favor_amount_formatted'] }}</td><td class="money">{{ $detail['against_amount_formatted'] }}</td><td>{{ $detail['origin_label'] }}</td><td>{{ $detail['origin_code'] ?: 'No aplica' }}</td></tr>@empty<tr><td colspan="6">Sin conceptos registrados.</td></tr>@endforelse</tbody></table>

        <div class="section-title">Trazabilidad del cierre</div>
        <table class="audit"><tr><td><span class="label">Calculado por</span><span class="value">{{ $closure->creator?->name ?: 'No aplica' }}</span><br><span class="muted">{{ optional($closure->created_at)->format('d/m/Y H:i') ?: 'No aplica' }}</span></td><td><span class="label">Confirmado por</span><span class="value">{{ $closure->closer?->name ?: 'No aplica' }}</span><br><span class="muted">{{ optional($closure->closed_at)->format('d/m/Y H:i') ?: 'No aplica' }}</span></td><td><span class="label">Método y referencia</span><span class="value">{{ $paymentLabel }}</span><br><span class="muted">{{ $closure->payment_method === 'efectivo' ? 'Referencia: No aplica' : 'Referencia: '.($closure->payment_reference ?: 'No aplica') }}</span></td></tr><tr><td><span class="label">Recibo generado</span><span class="value">{{ $closure->receipt?->receipt_number ?: 'No aplica' }}</span></td><td><span class="label">Movimiento de Caja</span><span class="value">{{ $movement?->movement_number ?: 'No aplica' }}</span></td><td><span class="label">Responsable</span><span class="value">{{ $closure->closer?->name ?: $closure->creator?->name ?: 'No aplica' }}</span></td></tr></table>

        @if($movement)<div class="section-title">Movimiento de Caja generado</div><div class="cash"><strong>{{ $movement->type === 'egreso' ? 'Egreso' : 'Ingreso' }} {{ $movement->movement_number }}</strong> por S/ {{ number_format((float) $movement->amount, 2) }}. Método: {{ $paymentLabel }}. Referencia: {{ $movement->payment_method === 'efectivo' ? 'No aplica' : ($movement->reference ?: 'No aplica') }}. Saldo posterior: {{ $movement->balance_after !== null ? 'S/ '.number_format((float) $movement->balance_after, 2) : 'No aplica' }}.</div>@endif

        <div class="section-title">Motivo y observaciones</div><div class="notes"><strong>Motivo:</strong> {{ $closure->reason ?: 'No aplica' }}<br><strong>Observación:</strong> {{ $closure->observation ?: 'No aplica' }}</div>

        @if($isAnnulled)<div class="section-title">Información de anulación</div><div class="notes"><strong>Anulado por:</strong> {{ $closure->annuller?->name ?: 'No aplica' }}<br><strong>Fecha de anulación:</strong> {{ optional($closure->annulled_at)->format('d/m/Y H:i') ?: 'No aplica' }}<br><strong>Motivo:</strong> {{ $closure->annulment_reason ?: 'No aplica' }}<br><strong>Movimiento de reversa:</strong> No aplica</div>@endif

        <table class="signatures avoid-break"><tr><td><div class="sign-line">Firma del socio<br><span class="muted">{{ $closure->member?->full_name ?: 'Socio' }}</span></div></td><td><div class="sign-line">Firma del responsable<br><span class="muted">{{ $closure->closer?->name ?: $closure->creator?->name ?: 'Responsable' }}</span></div></td></tr></table>
        <div class="footer">Documento financiero generado por SysCaC · {{ $closure->code }}</div>
    </div>
</body>
</html>
