<div class="modal fade cash-detail-modal" id="receiptDetailModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable" role="document"><div class="modal-content">
        <div class="modal-header member-modal-header"><div class="member-modal-titlebar"><div class="member-modal-icon"><i class="fas fa-receipt"></i></div><div><h5 class="modal-title mb-0">Detalle del recibo</h5><small>Constancia emitida por el sistema</small></div></div><button type="button" class="close ml-3" data-dismiss="modal"><span>&times;</span></button></div>
        <div class="modal-body member-modal-body">
            <div class="cash-detail-hero"><div><span>Recibo</span><h4 id="detailReceiptNumber">-</h4><p id="detailReceiptType">-</p></div><div id="detailReceiptStatus">-</div></div>
            <div class="cash-detail-summary"><div><span>Fecha</span><strong id="detailReceiptDate">-</strong></div><div><span>Socio</span><strong id="detailReceiptMember">-</strong></div><div><span>Monto</span><strong id="detailReceiptAmount">S/ 0.00</strong></div></div>
            <section class="member-detail-card"><h6><i class="fas fa-id-card"></i> Datos</h6><div class="member-detail-grid"><div><span>DNI</span><strong id="detailReceiptDni">-</strong></div><div><span>Codigo socio</span><strong id="detailReceiptMemberCode">-</strong></div><div><span>Metodo pago</span><strong id="detailReceiptMethod">-</strong></div><div><span>Referencia</span><strong id="detailReceiptReference">-</strong></div><div><span>Origen</span><strong id="detailReceiptOrigin">-</strong></div><div><span>Emitido por</span><strong id="detailReceiptUser">-</strong></div></div></section>
            <section class="member-detail-card"><h6><i class="fas fa-link"></i> Movimiento relacionado</h6><div class="member-detail-grid" id="detailReceiptOriginRows"></div></section>
            <section class="member-detail-card mb-0"><h6><i class="fas fa-file-alt"></i> Documentos</h6><div class="btn-group btn-group-sm mb-3"><a href="#" target="_blank" class="btn btn-light border disabled" id="detailReceiptPrint"><i class="fas fa-print mr-1"></i> Imprimir</a><a href="#" target="_blank" class="btn btn-light border disabled" id="detailReceiptPdf"><i class="fas fa-file-pdf mr-1"></i> PDF</a><a href="#" target="_blank" class="btn btn-light border disabled" id="detailReceiptVoucher"><i class="fas fa-paperclip mr-1"></i> Sin comprobante</a></div><div class="member-detail-note"><strong>Observacion</strong><br><span id="detailReceiptObservation">-</span></div></section>
        </div>
    </div></div>
</div>
