<div class="modal fade cash-modal" id="administrativeModal"><div class="modal-dialog modal-xl modal-dialog-centered"><div class="modal-content">
<div class="modal-header member-modal-header"><div class="member-modal-titlebar"><div class="member-modal-icon"><i class="fas fa-file-invoice-dollar"></i></div><div><h5 id="administrativeModalLabel" class="mb-0">Nuevo movimiento administrativo</h5><small>Control de ingresos y egresos del fondo</small></div></div><button class="close" data-dismiss="modal">&times;</button></div>
<form id="administrativeForm" enctype="multipart/form-data">@csrf<div class="modal-body member-modal-body"><div id="administrative-errors" class="alert alert-danger d-none"></div><div class="row">
<div class="col-lg-4"><aside class="cash-side-card"><span class="cash-side-kicker">Impacto en fondo</span><strong id="administrativeSideCode">{{$nextCode}}</strong><div class="cash-side-total"><span>Monto</span><strong id="administrativeSideAmount">S/ 0.00</strong></div><p>Los ingresos aumentan el fondo y los egresos lo disminuyen. Cada registro sincroniza Caja.</p></aside></div>
<div class="col-lg-8"><section class="member-section"><div class="member-section-header"><div><h6>Información del movimiento</h6><p>Código automático, fecha, tipo y socio opcional.</p></div></div>
<div class="form-row"><div class="form-group col-md-4"><label>Código</label><input name="code" value="{{$nextCode}}" class="form-control form-control-sm" readonly></div><div class="form-group col-md-4"><label>Fecha *</label><input type="date" name="movement_date" class="form-control form-control-sm" required></div><div class="form-group col-md-4"><label>Tipo *</label><select name="type" class="form-control form-control-sm" required><option value="ingreso">Ingreso</option><option value="egreso">Egreso</option></select></div></div>
<div class="form-group"><label>Socio relacionado</label><select name="member_id" class="form-control form-control-sm"><option value="">Sin socio relacionado</option>@foreach($members as $m)<option value="{{$m->id}}">{{$m->code}} - {{$m->full_name}}</option>@endforeach</select></div></section>
<section class="member-section"><div class="form-row"><div class="form-group col-md-6"><label>Concepto *</label><input name="concept" class="form-control form-control-sm" required></div><div class="form-group col-md-3"><label>Monto *</label><input type="number" min=".01" step=".01" name="amount" class="form-control form-control-sm" required></div><div class="form-group col-md-3"><label>Método *</label><select name="payment_method" class="form-control form-control-sm" required><option value="">Seleccione</option>@foreach($paymentMethods as $v=>$l)<option value="{{$v}}">{{$l}}</option>@endforeach</select></div></div><div class="form-group"><label>Referencia</label><input name="payment_reference" class="form-control form-control-sm"></div></section>
<section class="member-section"><label class="share-upload-box" for="administrativeVoucher"><i class="fas fa-paperclip"></i><span id="administrativeVoucherName">JPG, PNG, WEBP o PDF - max. 4 MB</span></label><input type="file" class="d-none" id="administrativeVoucher" name="voucher_path" accept="image/*,application/pdf"></section>
<section class="member-section mb-0"><label>Observación</label><textarea name="observation" class="form-control form-control-sm"></textarea></section></div></div></div>
<div class="modal-footer member-modal-footer"><button type="button" class="btn btn-light border" data-dismiss="modal">Cancelar</button><button class="btn btn-primary" type="submit"><i class="fas fa-save"></i> Guardar movimiento</button></div></form>
</div></div></div>
<div class="modal fade" id="administrativeAnnulModal"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5>Anular movimiento</h5><button class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><label>Motivo de anulación *</label><textarea id="administrativeCancellationReason" class="form-control" required></textarea></div><div class="modal-footer"><button class="btn btn-light" data-dismiss="modal">Cancelar</button><button id="confirmAdministrativeAnnul" class="btn btn-danger">Anular</button></div></div></div></div>
