<div class="modal fade cash-detail-modal" id="activityMovementDetailModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable" role="document"><div class="modal-content">
        <div class="modal-header member-modal-header"><div class="member-modal-titlebar"><div class="member-modal-icon"><i class="fas fa-exchange-alt"></i></div><div><h5 class="modal-title mb-0">Detalle de movimiento</h5><small>Movimiento de actividad, recibo y comprobante</small></div></div><button type="button" class="close ml-3" data-dismiss="modal"><span>&times;</span></button></div>
        <div class="modal-body member-modal-body">
            <div class="cash-detail-hero"><div><span>Movimiento</span><h4 id="detailActivityMovementCode">-</h4><p id="detailActivityMovementConcept">-</p></div><div id="detailActivityMovementStatus">-</div></div>
            <div class="cash-detail-summary"><div><span>Actividad</span><strong id="detailActivityMovementActivity">-</strong></div><div><span>Tipo</span><strong id="detailActivityMovementType">-</strong></div><div><span>Monto</span><strong id="detailActivityMovementAmount">S/ 0.00</strong></div></div>
            <div class="row">
                <div class="col-lg-6"><section class="member-detail-card"><h6><i class="fas fa-calendar-check"></i> Datos</h6><div class="member-detail-grid"><div><span>Fecha</span><strong id="detailActivityMovementDate">-</strong></div><div><span>Socio</span><strong id="detailActivityMovementMember">-</strong></div><div><span>DNI</span><strong id="detailActivityMovementDni">-</strong></div><div><span>Caja</span><strong id="detailActivityMovementCash">-</strong></div></div></section></div>
                <div class="col-lg-6"><section class="member-detail-card"><h6><i class="fas fa-credit-card"></i> Pago</h6><div class="member-detail-grid"><div><span>Metodo</span><strong id="detailActivityMovementPayment">-</strong></div><div><span>Referencia</span><strong id="detailActivityMovementReference">-</strong></div><div><span>Usuario</span><strong id="detailActivityMovementCreatedBy">-</strong></div><div><span>Registro</span><strong id="detailActivityMovementCreatedAt">-</strong></div></div></section></div>
                <div class="col-lg-6"><section class="member-detail-card"><h6><i class="fas fa-paperclip"></i> Comprobante</h6><div class="share-detail-links"><a href="#" id="detailActivityMovementVoucherView" class="btn btn-light border disabled" target="_blank" rel="noopener"><i class="fas fa-eye mr-1"></i> Sin comprobante</a><a href="#" id="detailActivityMovementVoucherDownload" class="btn btn-light border disabled"><i class="fas fa-download mr-1"></i> Descargar comprobante</a></div></section></div>
                <div class="col-lg-6"><section class="member-detail-card"><h6><i class="fas fa-receipt"></i> Recibo</h6><div class="share-detail-links"><a href="#" id="detailActivityMovementReceipt" class="btn btn-light border disabled" target="_blank" rel="noopener"><i class="fas fa-print mr-1"></i> Sin recibo</a><a href="#" id="detailActivityMovementReceiptPdf" class="btn btn-light border disabled" target="_blank" rel="noopener"><i class="fas fa-file-pdf mr-1"></i> PDF</a></div></section></div>
                <div class="col-12"><section class="member-detail-card mb-0"><h6><i class="fas fa-clipboard-list"></i> Observacion</h6><div id="detailActivityMovementObservation" class="member-detail-note">-</div></section></div>
            </div>
        </div>
    </div></div>
</div>
